import type { StaticFoodItem } from "./mena-foods";

export const WORLD_FOODS: StaticFoodItem[] = [
  // ── JAPAN ──────────────────────────────────────────────────────────────────
  {
    id: "jp-ramen",
    nameEn: "Tonkotsu Ramen",
    nameAr: "رامن تونكوتسو",
    cuisine: "Japanese",
    region: "East Asia",
    category: "soup",
    nutrition: { calories: 550, protein: 26, carbs: 62, fat: 22, fiber: 3, sodium: 1850 },
    tags: ["noodles", "pork-broth", "umami", "comfort-food"],
    allergens: ["wheat", "soy", "eggs"],
    cookTime: 240,
    difficulty: "hard",
    description: "Rich creamy pork-bone broth simmered for hours, with wheat noodles, chashu pork belly, soft-boiled egg and nori.",
    ingredients: ["ramen noodles", "pork bones", "chashu pork", "soft-boiled egg", "nori", "green onion", "bamboo shoots", "soy sauce", "mirin"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-sushi-roll",
    nameEn: "Sushi Roll (Maki)",
    nameAr: "لفائف السوشي",
    cuisine: "Japanese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 290, protein: 14, carbs: 48, fat: 5, fiber: 2, sodium: 620 },
    tags: ["raw-fish", "rice", "seaweed", "fresh"],
    allergens: ["fish", "soy", "wheat", "sesame"],
    cookTime: 40,
    difficulty: "medium",
    description: "Seasoned sushi rice and fresh fish or vegetables rolled tightly in nori seaweed, sliced into bite-sized rounds.",
    ingredients: ["sushi rice", "nori", "salmon or tuna", "cucumber", "avocado", "soy sauce", "wasabi", "pickled ginger", "rice vinegar"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-tonkatsu",
    nameEn: "Tonkatsu",
    nameAr: "تونكاتسو",
    cuisine: "Japanese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 520, protein: 32, carbs: 38, fat: 24, fiber: 2, sodium: 780 },
    tags: ["breaded-pork", "fried", "crispy", "comfort-food"],
    allergens: ["wheat", "eggs"],
    cookTime: 30,
    difficulty: "medium",
    description: "Thick pork cutlet coated in panko breadcrumbs and deep-fried to golden perfection, served with tangy tonkatsu sauce.",
    ingredients: ["pork loin", "panko breadcrumbs", "egg", "flour", "cabbage", "tonkatsu sauce", "rice"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-miso-soup",
    nameEn: "Miso Soup",
    nameAr: "شوربة الميسو",
    cuisine: "Japanese",
    region: "East Asia",
    category: "soup",
    nutrition: { calories: 75, protein: 5, carbs: 6, fat: 3, fiber: 1, sodium: 640 },
    tags: ["fermented", "light", "umami", "daily-staple"],
    allergens: ["soy", "fish"],
    cookTime: 10,
    difficulty: "easy",
    description: "Warming dashi broth enriched with fermented soybean paste, silken tofu and wakame seaweed — Japan's daily staple soup.",
    ingredients: ["miso paste", "dashi stock", "tofu", "wakame seaweed", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-gyoza",
    nameEn: "Gyoza",
    nameAr: "غيوزا",
    cuisine: "Japanese",
    region: "East Asia",
    category: "appetizer",
    nutrition: { calories: 310, protein: 14, carbs: 32, fat: 14, fiber: 2, sodium: 690 },
    tags: ["dumplings", "crispy", "pork", "pan-fried"],
    allergens: ["wheat", "soy", "sesame"],
    cookTime: 25,
    difficulty: "medium",
    description: "Thin-skinned pan-fried dumplings filled with pork, cabbage and garlic, crispy on the bottom and steamy inside.",
    ingredients: ["gyoza wrappers", "ground pork", "cabbage", "garlic", "ginger", "soy sauce", "sesame oil", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-tempura",
    nameEn: "Tempura",
    nameAr: "تمبورا",
    cuisine: "Japanese",
    region: "East Asia",
    category: "appetizer",
    nutrition: { calories: 380, protein: 18, carbs: 42, fat: 16, fiber: 2, sodium: 520 },
    tags: ["battered", "fried", "light", "seafood"],
    allergens: ["wheat", "eggs", "shellfish"],
    cookTime: 25,
    difficulty: "medium",
    description: "Light, airy battered shrimp and vegetables deep-fried at high temperature, served with tsuyu dipping sauce.",
    ingredients: ["shrimp", "sweet potato", "zucchini", "flour", "egg", "ice water", "dashi", "mirin", "soy sauce"],
    source: "nutri-llm-library",
  },

  // ── KOREA ──────────────────────────────────────────────────────────────────
  {
    id: "kr-bibimbap",
    nameEn: "Bibimbap",
    nameAr: "بيبيمباب",
    cuisine: "Korean",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 490, protein: 20, carbs: 68, fat: 14, fiber: 5, sodium: 780 },
    tags: ["rice-bowl", "colorful", "healthy", "mixed"],
    allergens: ["eggs", "soy", "sesame"],
    cookTime: 40,
    difficulty: "medium",
    description: "A vibrant bowl of warm rice topped with seasoned vegetables, gochujang sauce, a fried egg and sesame oil.",
    ingredients: ["rice", "spinach", "carrots", "bean sprouts", "shiitake", "beef", "egg", "gochujang", "sesame oil", "garlic"],
    source: "nutri-llm-library",
  },
  {
    id: "kr-bulgogi",
    nameEn: "Bulgogi",
    nameAr: "بولغوغي",
    cuisine: "Korean",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 390, protein: 32, carbs: 22, fat: 18, fiber: 1, sodium: 720 },
    tags: ["marinated-beef", "grilled", "sweet-savory", "bbq"],
    allergens: ["soy", "sesame", "wheat"],
    cookTime: 30,
    difficulty: "easy",
    description: "Thinly sliced marinated beef grilled over open flame — sweet, savory, and smoky. Korea's most beloved BBQ.",
    ingredients: ["beef sirloin", "soy sauce", "sugar", "pear", "garlic", "ginger", "sesame oil", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "kr-kimchi-jjigae",
    nameEn: "Kimchi Jjigae",
    nameAr: "يخنة الكيمتشي",
    cuisine: "Korean",
    region: "East Asia",
    category: "soup",
    nutrition: { calories: 280, protein: 18, carbs: 18, fat: 12, fiber: 4, sodium: 980 },
    tags: ["fermented", "spicy", "pork", "stew"],
    allergens: ["soy", "shellfish"],
    cookTime: 30,
    difficulty: "easy",
    description: "Fiery stew made with aged kimchi, pork belly, silken tofu and gochugaru — deep, funky, intensely satisfying.",
    ingredients: ["kimchi", "pork belly", "tofu", "onion", "garlic", "gochugaru", "soy sauce", "sesame oil", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "kr-tteokbokki",
    nameEn: "Tteokbokki",
    nameAr: "توكبوكي",
    cuisine: "Korean",
    region: "East Asia",
    category: "snack",
    nutrition: { calories: 350, protein: 8, carbs: 62, fat: 7, fiber: 2, sodium: 920 },
    tags: ["rice-cakes", "spicy", "street-food", "chewy"],
    allergens: ["wheat", "soy", "eggs"],
    cookTime: 20,
    difficulty: "easy",
    description: "Chewy cylinder rice cakes tossed in a fiery-sweet gochujang sauce with fish cakes and green onions.",
    ingredients: ["rice cakes", "gochujang", "gochugaru", "fish cake", "green onion", "sugar", "soy sauce", "sesame seeds"],
    source: "nutri-llm-library",
  },

  // ── INDIA ──────────────────────────────────────────────────────────────────
  {
    id: "in-butter-chicken",
    nameEn: "Butter Chicken",
    nameAr: "دجاج بالزبدة",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 490, protein: 34, carbs: 20, fat: 28, fiber: 3, sodium: 740 },
    tags: ["curry", "creamy-tomato", "mild", "popular"],
    allergens: ["dairy"],
    cookTime: 50,
    difficulty: "medium",
    description: "Tender chicken in a velvety tomato-cream sauce spiced with fenugreek, garam masala, and butter — the world's favourite curry.",
    ingredients: ["chicken", "tomatoes", "butter", "cream", "onion", "garlic", "ginger", "garam masala", "fenugreek", "paprika"],
    source: "nutri-llm-library",
  },
  {
    id: "in-biryani",
    nameEn: "Biryani",
    nameAr: "برياني",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 620, protein: 30, carbs: 72, fat: 22, fiber: 3, sodium: 860 },
    tags: ["fragrant-rice", "saffron", "layered", "celebratory"],
    allergens: ["dairy"],
    cookTime: 90,
    difficulty: "hard",
    description: "Aromatic long-grain rice layered with marinated meat, fried onions, saffron milk, and whole spices — sealed and slow-cooked.",
    ingredients: ["basmati rice", "chicken or lamb", "yogurt", "saffron", "fried onions", "ghee", "garam masala", "mint", "rose water"],
    source: "nutri-llm-library",
  },
  {
    id: "in-dal-makhani",
    nameEn: "Dal Makhani",
    nameAr: "عدس الماخاني",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 370, protein: 16, carbs: 45, fat: 15, fiber: 12, sodium: 580 },
    tags: ["lentils", "creamy", "slow-cooked", "vegetarian"],
    allergens: ["dairy"],
    cookTime: 180,
    difficulty: "medium",
    description: "Whole black lentils and kidney beans slow-simmered overnight in tomato, butter and cream — silky, smoky and deeply nourishing.",
    ingredients: ["black lentils", "kidney beans", "butter", "cream", "tomatoes", "onion", "garlic", "ginger", "garam masala"],
    source: "nutri-llm-library",
  },
  {
    id: "in-dosa",
    nameEn: "Masala Dosa",
    nameAr: "دوسا بالبطاطا",
    cuisine: "South Indian",
    region: "South Asia",
    category: "breakfast",
    nutrition: { calories: 350, protein: 8, carbs: 55, fat: 12, fiber: 4, sodium: 420 },
    tags: ["fermented", "crispy", "crepe", "vegan"],
    allergens: [],
    cookTime: 30,
    difficulty: "hard",
    description: "Enormous crispy fermented rice-lentil crepe filled with spiced potato masala, served with coconut chutney and sambar.",
    ingredients: ["rice", "urad dal", "potatoes", "mustard seeds", "curry leaves", "turmeric", "coconut chutney", "sambar"],
    source: "nutri-llm-library",
  },
  {
    id: "in-palak-paneer",
    nameEn: "Palak Paneer",
    nameAr: "بانير السبانخ",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 340, protein: 16, carbs: 18, fat: 22, fiber: 5, sodium: 560 },
    tags: ["spinach", "cottage-cheese", "vegetarian", "creamy"],
    allergens: ["dairy"],
    cookTime: 35,
    difficulty: "easy",
    description: "Fresh paneer cubes bathed in a smooth, gently spiced spinach sauce — vibrant green, hearty and vegetarian.",
    ingredients: ["paneer", "spinach", "onion", "tomatoes", "cream", "garlic", "ginger", "cumin", "garam masala", "butter"],
    source: "nutri-llm-library",
  },
  {
    id: "in-chana-masala",
    nameEn: "Chana Masala",
    nameAr: "حمص بالتوابل الهندية",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 300, protein: 15, carbs: 44, fat: 9, fiber: 11, sodium: 490 },
    tags: ["chickpeas", "vegan", "spiced", "high-fiber"],
    allergens: [],
    cookTime: 40,
    difficulty: "medium",
    description: "Robust Punjabi chickpea curry in a tangy, deeply spiced tomato sauce with amchur, pomegranate and chaat masala.",
    ingredients: ["chickpeas", "tomatoes", "onion", "garlic", "ginger", "cumin", "coriander", "garam masala", "amchur", "green chili"],
    source: "nutri-llm-library",
  },

  // ── SOUTHEAST ASIA ─────────────────────────────────────────────────────────
  {
    id: "vn-pho",
    nameEn: "Pho Bo",
    nameAr: "فو",
    cuisine: "Vietnamese",
    region: "Southeast Asia",
    category: "soup",
    nutrition: { calories: 390, protein: 24, carbs: 52, fat: 8, fiber: 2, sodium: 1100 },
    tags: ["noodle-soup", "beef", "herbs", "aromatic"],
    allergens: ["wheat", "soy"],
    cookTime: 360,
    difficulty: "hard",
    description: "Vietnam's soul food — a clear, star-anise scented beef bone broth with rice noodles, herbs, bean sprouts and lime.",
    ingredients: ["beef bones", "rice noodles", "star anise", "cinnamon", "ginger", "onion", "bean sprouts", "basil", "lime", "hoisin sauce"],
    source: "nutri-llm-library",
  },
  {
    id: "vn-banh-mi",
    nameEn: "Bánh Mì",
    nameAr: "بانه مي",
    cuisine: "Vietnamese",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 450, protein: 22, carbs: 56, fat: 16, fiber: 3, sodium: 880 },
    tags: ["baguette", "fusion", "pickled", "street-food"],
    allergens: ["wheat", "soy", "eggs"],
    cookTime: 20,
    difficulty: "easy",
    description: "A French-Vietnamese fusion in a crusty baguette — filled with pork, pâté, pickled daikon, cilantro and jalapeño.",
    ingredients: ["baguette", "pork belly or pate", "pickled daikon", "pickled carrot", "cucumber", "jalapeño", "cilantro", "mayo", "soy sauce"],
    source: "nutri-llm-library",
  },
  {
    id: "th-green-curry",
    nameEn: "Thai Green Curry",
    nameAr: "كاري أخضر تايلاندي",
    cuisine: "Thai",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 440, protein: 26, carbs: 20, fat: 28, fiber: 3, sodium: 820 },
    tags: ["coconut-milk", "spicy", "aromatic", "thai"],
    allergens: ["shellfish", "fish"],
    cookTime: 30,
    difficulty: "medium",
    description: "Fragrant Thai curry in coconut milk with green chili paste, eggplant, chicken and kaffir lime — fresh and fiery.",
    ingredients: ["chicken", "coconut milk", "green curry paste", "eggplant", "bamboo shoots", "kaffir lime leaves", "fish sauce", "palm sugar", "basil"],
    source: "nutri-llm-library",
  },
  {
    id: "th-tom-yum",
    nameEn: "Tom Yum Goong",
    nameAr: "توم يوم جونج",
    cuisine: "Thai",
    region: "Southeast Asia",
    category: "soup",
    nutrition: { calories: 180, protein: 18, carbs: 8, fat: 8, fiber: 2, sodium: 980 },
    tags: ["spicy-sour", "shrimp", "lemongrass", "low-calorie"],
    allergens: ["shellfish", "fish"],
    cookTime: 25,
    difficulty: "medium",
    description: "Thailand's iconic hot and sour shrimp soup — lemongrass, galangal, kaffir lime, fish sauce and fiery bird's eye chili.",
    ingredients: ["shrimp", "lemongrass", "galangal", "kaffir lime leaves", "bird's eye chili", "fish sauce", "lime juice", "mushrooms", "tomatoes"],
    source: "nutri-llm-library",
  },
  {
    id: "id-nasi-goreng",
    nameEn: "Nasi Goreng",
    nameAr: "ناسي غورينج",
    cuisine: "Indonesian",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 510, protein: 18, carbs: 68, fat: 18, fiber: 3, sodium: 860 },
    tags: ["fried-rice", "shrimp-paste", "egg", "street-food"],
    allergens: ["eggs", "soy", "shellfish"],
    cookTime: 20,
    difficulty: "easy",
    description: "Indonesia's beloved fried rice made with kecap manis, shrimp paste and chili, topped with a fried egg and kerupuk crackers.",
    ingredients: ["rice", "eggs", "shrimp", "kecap manis", "shrimp paste", "garlic", "shallots", "chili", "cabbage", "tomato"],
    source: "nutri-llm-library",
  },

  // ── CHINA ──────────────────────────────────────────────────────────────────
  {
    id: "cn-kung-pao",
    nameEn: "Kung Pao Chicken",
    nameAr: "دجاج كونغ باو",
    cuisine: "Chinese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 420, protein: 30, carbs: 24, fat: 22, fiber: 3, sodium: 960 },
    tags: ["spicy", "stir-fry", "peanuts", "sichuan"],
    allergens: ["peanuts", "soy", "wheat"],
    cookTime: 25,
    difficulty: "medium",
    description: "Sichuan stir-fried diced chicken with peanuts, dried chilies, Sichuan pepper and a glossy sweet-spicy sauce.",
    ingredients: ["chicken", "peanuts", "dried chilies", "sichuan pepper", "soy sauce", "vinegar", "sugar", "garlic", "ginger", "zucchini"],
    source: "nutri-llm-library",
  },
  {
    id: "cn-mapo-tofu",
    nameEn: "Mapo Tofu",
    nameAr: "توفو مابو",
    cuisine: "Chinese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 310, protein: 20, carbs: 14, fat: 18, fiber: 2, sodium: 880 },
    tags: ["silken-tofu", "spicy", "numbing", "sichuan"],
    allergens: ["soy", "wheat"],
    cookTime: 20,
    difficulty: "medium",
    description: "Silken tofu in a fiery, numbing sauce of black bean paste, Sichuan pepper, minced pork and doubanjiang.",
    ingredients: ["silken tofu", "ground pork", "doubanjiang", "black bean paste", "sichuan pepper", "garlic", "ginger", "broth", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "cn-dim-sum",
    nameEn: "Dim Sum (Har Gow)",
    nameAr: "هار قاو",
    cuisine: "Cantonese",
    region: "East Asia",
    category: "appetizer",
    nutrition: { calories: 200, protein: 12, carbs: 24, fat: 6, fiber: 1, sodium: 480 },
    tags: ["dumplings", "steamed", "shrimp", "yum-cha"],
    allergens: ["wheat", "shellfish"],
    cookTime: 45,
    difficulty: "hard",
    description: "Translucent steamed shrimp dumplings — delicate pleated wrappers with a juicy whole shrimp filling inside.",
    ingredients: ["wheat starch", "shrimp", "bamboo shoots", "sesame oil", "soy sauce", "ginger", "white pepper"],
    source: "nutri-llm-library",
  },
  {
    id: "cn-peking-duck",
    nameEn: "Peking Duck",
    nameAr: "البط البكيني",
    cuisine: "Chinese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 560, protein: 34, carbs: 28, fat: 34, fiber: 1, sodium: 820 },
    tags: ["crispy-skin", "duck", "imperial", "festive"],
    allergens: ["wheat", "soy", "sesame"],
    cookTime: 480,
    difficulty: "hard",
    description: "Beijing's legendary roasted duck with lacquered mahogany skin, served with thin pancakes, hoisin sauce and cucumber.",
    ingredients: ["whole duck", "pancakes", "hoisin sauce", "cucumber", "green onion", "maltose", "five-spice", "soy sauce"],
    source: "nutri-llm-library",
  },

  // ── ITALY ──────────────────────────────────────────────────────────────────
  {
    id: "it-carbonara",
    nameEn: "Pasta Carbonara",
    nameAr: "باستا كاربونارا",
    cuisine: "Italian",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 560, protein: 26, carbs: 62, fat: 22, fiber: 3, sodium: 680 },
    tags: ["pasta", "eggs", "pecorino", "guanciale"],
    allergens: ["wheat", "eggs", "dairy"],
    cookTime: 25,
    difficulty: "medium",
    description: "Rome's iconic pasta — guanciale cured pork, eggs and Pecorino Romano cheese create a silky, emulsified sauce without cream.",
    ingredients: ["spaghetti", "guanciale", "eggs", "Pecorino Romano", "black pepper", "salt"],
    source: "nutri-llm-library",
  },
  {
    id: "it-pizza-margherita",
    nameEn: "Pizza Margherita",
    nameAr: "بيتزا مارغريتا",
    cuisine: "Italian",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 500, protein: 18, carbs: 68, fat: 18, fiber: 4, sodium: 820 },
    tags: ["neapolitan", "tomato", "mozzarella", "basil"],
    allergens: ["wheat", "dairy"],
    cookTime: 90,
    difficulty: "medium",
    description: "The original Neapolitan pizza — San Marzano tomatoes, fresh buffalo mozzarella and basil on a charred wood-fired crust.",
    ingredients: ["pizza dough", "San Marzano tomatoes", "buffalo mozzarella", "fresh basil", "olive oil", "salt"],
    source: "nutri-llm-library",
  },
  {
    id: "it-risotto",
    nameEn: "Risotto ai Funghi",
    nameAr: "ريزوتو الفطر",
    cuisine: "Italian",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 440, protein: 12, carbs: 58, fat: 16, fiber: 3, sodium: 560 },
    tags: ["arborio-rice", "porcini", "creamy", "vegetarian"],
    allergens: ["dairy"],
    cookTime: 40,
    difficulty: "medium",
    description: "Silky, slow-stirred arborio rice with porcini mushrooms, white wine, Parmesan and butter — the art of northern Italian cooking.",
    ingredients: ["arborio rice", "porcini mushrooms", "shallots", "white wine", "Parmesan", "butter", "vegetable broth", "thyme"],
    source: "nutri-llm-library",
  },
  {
    id: "it-tiramisu",
    nameEn: "Tiramisù",
    nameAr: "تيراميسو",
    cuisine: "Italian",
    region: "Mediterranean",
    category: "dessert",
    nutrition: { calories: 410, protein: 9, carbs: 38, fat: 24, fiber: 0, sodium: 120 },
    tags: ["coffee", "mascarpone", "ladyfingers", "no-bake"],
    allergens: ["dairy", "eggs", "wheat"],
    cookTime: 30,
    difficulty: "medium",
    description: "Coffee-soaked savoiardi biscuits layered with whipped mascarpone and egg cream, dusted with bitter cocoa.",
    ingredients: ["mascarpone", "eggs", "sugar", "ladyfinger biscuits", "espresso", "Marsala wine", "cocoa powder"],
    source: "nutri-llm-library",
  },

  // ── MEXICO ─────────────────────────────────────────────────────────────────
  {
    id: "mx-tacos-pastor",
    nameEn: "Tacos al Pastor",
    nameAr: "تاكو الراعي",
    cuisine: "Mexican",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 370, protein: 22, carbs: 38, fat: 14, fiber: 3, sodium: 640 },
    tags: ["pork", "pineapple", "achiote", "street-food"],
    allergens: ["wheat"],
    cookTime: 120,
    difficulty: "medium",
    description: "Marinated pork trompo sliced thin and served in corn tortillas with pineapple, onion and cilantro — a Mexico City icon.",
    ingredients: ["pork shoulder", "achiote", "dried chilies", "pineapple", "corn tortillas", "onion", "cilantro", "lime", "guajillo"],
    source: "nutri-llm-library",
  },
  {
    id: "mx-guacamole",
    nameEn: "Guacamole",
    nameAr: "جواكامولي",
    cuisine: "Mexican",
    region: "Latin America",
    category: "appetizer",
    nutrition: { calories: 240, protein: 3, carbs: 12, fat: 20, fiber: 7, sodium: 300 },
    tags: ["avocado", "fresh", "vegan", "healthy-fats"],
    allergens: [],
    cookTime: 10,
    difficulty: "easy",
    description: "Freshly mashed Hass avocados with lime, red onion, cilantro, jalapeño and salt — the world's most beloved dip.",
    ingredients: ["avocado", "lime juice", "red onion", "cilantro", "jalapeño", "tomato", "salt", "garlic"],
    source: "nutri-llm-library",
  },
  {
    id: "mx-mole-negro",
    nameEn: "Mole Negro",
    nameAr: "موله نيغرو",
    cuisine: "Mexican",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 490, protein: 32, carbs: 28, fat: 26, fiber: 6, sodium: 580 },
    tags: ["chocolate", "chili", "complex-sauce", "oaxacan"],
    allergens: ["tree nuts", "sesame", "wheat"],
    cookTime: 240,
    difficulty: "hard",
    description: "Oaxaca's breathtaking black sauce — over 30 ingredients including multiple dried chilies, chocolate, nuts and spices over turkey or chicken.",
    ingredients: ["turkey or chicken", "mulato chilies", "ancho chilies", "dark chocolate", "almonds", "sesame", "tomato", "plantain", "spices"],
    source: "nutri-llm-library",
  },

  // ── NIGERIA / WEST AFRICA ───────────────────────────────────────────────────
  {
    id: "ng-jollof-rice",
    nameEn: "Jollof Rice",
    nameAr: "أرز جولوف",
    cuisine: "West African",
    region: "West Africa",
    category: "main",
    nutrition: { calories: 480, protein: 18, carbs: 72, fat: 14, fiber: 4, sodium: 740 },
    tags: ["one-pot", "tomato", "smoky", "celebratory"],
    allergens: [],
    cookTime: 60,
    difficulty: "medium",
    description: "West Africa's iconic one-pot rice — slow-cooked in a rich, smoky tomato, pepper and onion base with chicken or beef.",
    ingredients: ["long-grain rice", "tomatoes", "bell peppers", "scotch bonnet", "onion", "chicken", "tomato paste", "bay leaves", "thyme"],
    source: "nutri-llm-library",
  },
  {
    id: "ng-egusi-soup",
    nameEn: "Egusi Soup",
    nameAr: "شوربة الأغوسي",
    cuisine: "Nigerian",
    region: "West Africa",
    category: "soup",
    nutrition: { calories: 460, protein: 22, carbs: 14, fat: 34, fiber: 5, sodium: 620 },
    tags: ["melon-seeds", "leafy-greens", "palm-oil", "protein-rich"],
    allergens: [],
    cookTime: 60,
    difficulty: "medium",
    description: "Hearty Nigerian soup of ground melon seeds cooked in palm oil with assorted meats, leafy greens and crayfish.",
    ingredients: ["egusi (melon seeds)", "palm oil", "beef", "stockfish", "crayfish", "ugwu leaves", "onion", "pepper", "seasoning"],
    source: "nutri-llm-library",
  },
  {
    id: "ng-suya",
    nameEn: "Suya",
    nameAr: "سويا",
    cuisine: "Nigerian",
    region: "West Africa",
    category: "snack",
    nutrition: { calories: 340, protein: 28, carbs: 8, fat: 22, fiber: 2, sodium: 490 },
    tags: ["grilled", "spiced-beef", "street-food", "peanut"],
    allergens: ["peanuts"],
    cookTime: 30,
    difficulty: "medium",
    description: "Skewered and charcoal-grilled spiced beef coated in yaji — a dry rub of ground peanuts, ginger, paprika and garlic.",
    ingredients: ["beef sirloin", "peanuts", "ginger", "paprika", "garlic powder", "onion powder", "crayfish", "suya spice"],
    source: "nutri-llm-library",
  },

  // ── ETHIOPIA ───────────────────────────────────────────────────────────────
  {
    id: "et-doro-wat",
    nameEn: "Doro Wat",
    nameAr: "دورو وات",
    cuisine: "Ethiopian",
    region: "East Africa",
    category: "main",
    nutrition: { calories: 410, protein: 30, carbs: 14, fat: 24, fiber: 3, sodium: 620 },
    tags: ["berbere-spice", "chicken-stew", "eggs", "spicy"],
    allergens: ["eggs"],
    cookTime: 120,
    difficulty: "hard",
    description: "Ethiopia's national dish — chicken legs simmered in a deeply spiced berbere butter sauce with hard-boiled eggs.",
    ingredients: ["chicken", "berbere spice", "niter kibbeh", "onion", "garlic", "ginger", "hard-boiled eggs", "wine"],
    source: "nutri-llm-library",
  },
  {
    id: "et-injera",
    nameEn: "Injera",
    nameAr: "إنجيرا",
    cuisine: "Ethiopian",
    region: "East Africa",
    category: "side",
    nutrition: { calories: 180, protein: 5, carbs: 36, fat: 1, fiber: 2, sodium: 180 },
    tags: ["sourdough-flatbread", "fermented", "teff", "gluten-sensitive"],
    allergens: [],
    cookTime: 1440,
    difficulty: "hard",
    description: "Spongy, tangy sourdough flatbread made from teff flour — both plate and utensil for Ethiopian stews and salads.",
    ingredients: ["teff flour", "water", "salt"],
    source: "nutri-llm-library",
  },

  // ── PERU ───────────────────────────────────────────────────────────────────
  {
    id: "pe-ceviche",
    nameEn: "Ceviche",
    nameAr: "سيفيتشي",
    cuisine: "Peruvian",
    region: "Latin America",
    category: "appetizer",
    nutrition: { calories: 220, protein: 28, carbs: 12, fat: 4, fiber: 2, sodium: 680 },
    tags: ["raw-fish", "citrus-cured", "fresh", "light"],
    allergens: ["fish", "shellfish"],
    cookTime: 20,
    difficulty: "easy",
    description: "Fresh raw fish cured in lime juice with red onion, chili and cilantro — served with choclo corn and sweet potato.",
    ingredients: ["white fish or shrimp", "lime juice", "red onion", "aji amarillo", "cilantro", "choclo", "sweet potato", "salt"],
    source: "nutri-llm-library",
  },
  {
    id: "pe-lomo-saltado",
    nameEn: "Lomo Saltado",
    nameAr: "لومو سالتادو",
    cuisine: "Peruvian",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 510, protein: 30, carbs: 42, fat: 22, fiber: 4, sodium: 780 },
    tags: ["stir-fry", "beef", "fusion", "chifa"],
    allergens: ["soy", "wheat"],
    cookTime: 30,
    difficulty: "medium",
    description: "Peru's Chinese-influenced stir-fry of beef, tomatoes, aji amarillo and onions, served with fries and rice.",
    ingredients: ["beef sirloin", "tomatoes", "red onion", "aji amarillo", "soy sauce", "oyster sauce", "french fries", "rice", "cilantro"],
    source: "nutri-llm-library",
  },

  // ── GREECE ─────────────────────────────────────────────────────────────────
  {
    id: "gr-moussaka",
    nameEn: "Moussaka",
    nameAr: "مسقعة",
    cuisine: "Greek",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 520, protein: 28, carbs: 30, fat: 32, fiber: 4, sodium: 680 },
    tags: ["eggplant", "béchamel", "layered", "baked"],
    allergens: ["dairy", "eggs", "wheat"],
    cookTime: 120,
    difficulty: "hard",
    description: "Greece's beloved baked casserole — layers of eggplant, spiced lamb mince and golden béchamel sauce.",
    ingredients: ["eggplant", "ground lamb", "potatoes", "tomatoes", "cinnamon", "milk", "butter", "flour", "eggs", "Kefalotyri cheese"],
    source: "nutri-llm-library",
  },
  {
    id: "gr-souvlaki",
    nameEn: "Souvlaki",
    nameAr: "سوفلاكي",
    cuisine: "Greek",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 380, protein: 28, carbs: 32, fat: 16, fiber: 2, sodium: 560 },
    tags: ["grilled-meat", "pita", "tzatziki", "street-food"],
    allergens: ["dairy", "wheat"],
    cookTime: 30,
    difficulty: "easy",
    description: "Juicy marinated pork or chicken skewers wrapped in warm pita with tzatziki, tomato, onion and paprika fries.",
    ingredients: ["pork or chicken", "pita bread", "tzatziki", "tomato", "red onion", "paprika", "lemon", "oregano", "olive oil"],
    source: "nutri-llm-library",
  },

  // ── USA ────────────────────────────────────────────────────────────────────
  {
    id: "us-bbq-ribs",
    nameEn: "BBQ Pork Ribs",
    nameAr: "ضلوع لحم الخنزير المشوية",
    cuisine: "American",
    region: "North America",
    category: "main",
    nutrition: { calories: 620, protein: 40, carbs: 18, fat: 42, fiber: 1, sodium: 860 },
    tags: ["smoked", "bbq-sauce", "slow-cooked", "ribs"],
    allergens: [],
    cookTime: 360,
    difficulty: "hard",
    description: "Low-and-slow smoked pork ribs lacquered in a tangy, sweet BBQ sauce — fall-off-the-bone tender with a smoky bark.",
    ingredients: ["pork spare ribs", "BBQ sauce", "brown sugar", "paprika", "garlic powder", "cumin", "cayenne", "apple cider vinegar"],
    source: "nutri-llm-library",
  },
  {
    id: "us-clam-chowder",
    nameEn: "New England Clam Chowder",
    nameAr: "شوربة البطلينوس",
    cuisine: "American",
    region: "North America",
    category: "soup",
    nutrition: { calories: 330, protein: 14, carbs: 28, fat: 18, fiber: 2, sodium: 980 },
    tags: ["creamy", "clams", "potatoes", "seafood"],
    allergens: ["dairy", "shellfish", "wheat"],
    cookTime: 40,
    difficulty: "medium",
    description: "Boston's thick, cream-based chowder loaded with tender clams, potatoes and smoky bacon in every spoonful.",
    ingredients: ["clams", "cream", "potatoes", "bacon", "onion", "celery", "flour", "butter", "bay leaves", "thyme"],
    source: "nutri-llm-library",
  },

  // ── SPAIN ──────────────────────────────────────────────────────────────────
  {
    id: "es-paella",
    nameEn: "Paella Valenciana",
    nameAr: "باييلا",
    cuisine: "Spanish",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 530, protein: 28, carbs: 68, fat: 16, fiber: 3, sodium: 780 },
    tags: ["saffron-rice", "seafood", "socarrat", "festive"],
    allergens: ["shellfish", "fish"],
    cookTime: 60,
    difficulty: "hard",
    description: "Valencia's iconic wide-pan rice dish with rabbit, chicken, seafood, green beans and a crispy socarrat base.",
    ingredients: ["bomba rice", "chicken", "rabbit or shrimp", "mussels", "saffron", "tomatoes", "green beans", "paprika", "olive oil"],
    source: "nutri-llm-library",
  },

  // ── FRANCE ─────────────────────────────────────────────────────────────────
  {
    id: "fr-croissant",
    nameEn: "Croissant",
    nameAr: "كرواسون",
    cuisine: "French",
    region: "Western Europe",
    category: "breakfast",
    nutrition: { calories: 270, protein: 5, carbs: 30, fat: 14, fiber: 1, sodium: 310 },
    tags: ["laminated-dough", "buttery", "flaky", "viennoiserie"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 300,
    difficulty: "hard",
    description: "Flaky, buttery crescents of laminated yeast dough with hundreds of paper-thin layers — the pinnacle of French pastry.",
    ingredients: ["flour", "butter", "yeast", "milk", "sugar", "salt", "egg"],
    source: "nutri-llm-library",
  },

  // ── BRAZIL ─────────────────────────────────────────────────────────────────
  {
    id: "br-feijoada",
    nameEn: "Feijoada",
    nameAr: "فيجوادا",
    cuisine: "Brazilian",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 560, protein: 30, carbs: 48, fat: 22, fiber: 12, sodium: 840 },
    tags: ["black-beans", "pork", "hearty", "national-dish"],
    allergens: [],
    cookTime: 180,
    difficulty: "medium",
    description: "Brazil's national dish — a hearty slow-cooked stew of black beans with smoked sausages, pork ribs and beef served over rice.",
    ingredients: ["black beans", "smoked sausage", "cured pork", "beef ribs", "onion", "garlic", "bay leaves", "orange zest", "farofa"],
    source: "nutri-llm-library",
  },

  // ── GERMANY ────────────────────────────────────────────────────────────────
  {
    id: "de-schnitzel",
    nameEn: "Wiener Schnitzel",
    nameAr: "شنيتزل",
    cuisine: "German",
    region: "Central Europe",
    category: "main",
    nutrition: { calories: 490, protein: 30, carbs: 34, fat: 24, fiber: 2, sodium: 620 },
    tags: ["breaded-veal", "fried", "crispy", "classic"],
    allergens: ["wheat", "eggs", "dairy"],
    cookTime: 30,
    difficulty: "medium",
    description: "Paper-thin breaded and pan-fried veal cutlet, served with lemon and potato salad — Austria and Germany's iconic dish.",
    ingredients: ["veal cutlet", "breadcrumbs", "egg", "flour", "clarified butter", "lemon", "parsley"],
    source: "nutri-llm-library",
  },
  {
    id: "de-bratwurst",
    nameEn: "Bratwurst",
    nameAr: "براتفورست",
    cuisine: "German",
    region: "Central Europe",
    category: "main",
    nutrition: { calories: 400, protein: 18, carbs: 4, fat: 34, fiber: 0, sodium: 740 },
    tags: ["sausage", "grilled", "pork", "street-food"],
    allergens: [],
    cookTime: 20,
    difficulty: "easy",
    description: "Juicy grilled pork sausage with a snappy casing — served in a bread roll with mustard at German markets and festivals.",
    ingredients: ["pork", "pork fat", "marjoram", "nutmeg", "ginger", "cardamom", "salt", "bread roll", "mustard"],
    source: "nutri-llm-library",
  },
  {
    id: "de-pretzel",
    nameEn: "Bavarian Pretzel",
    nameAr: "بريتزل بافاري",
    cuisine: "German",
    region: "Central Europe",
    category: "snack",
    nutrition: { calories: 340, protein: 10, carbs: 60, fat: 6, fiber: 2, sodium: 980 },
    tags: ["baked", "salted", "chewy", "beer-garden"],
    allergens: ["wheat", "dairy"],
    cookTime: 90,
    difficulty: "medium",
    description: "Dark, glossy and chewy Bavarian brezn dipped in lye solution before baking — crusted with coarse salt and served with sweet mustard.",
    ingredients: ["flour", "butter", "yeast", "water", "baking soda", "coarse salt", "sweet mustard"],
    source: "nutri-llm-library",
  },
  {
    id: "de-apple-strudel",
    nameEn: "Apple Strudel",
    nameAr: "ستروديل التفاح",
    cuisine: "Austrian",
    region: "Central Europe",
    category: "dessert",
    nutrition: { calories: 310, protein: 4, carbs: 52, fat: 10, fiber: 3, sodium: 160 },
    tags: ["pastry", "apple", "cinnamon", "baked"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 90,
    difficulty: "hard",
    description: "Wafer-thin hand-stretched dough wrapped around a spiced apple, raisin and walnut filling — Austria's most beloved pastry.",
    ingredients: ["phyllo dough", "apples", "sugar", "cinnamon", "raisins", "breadcrumbs", "butter", "lemon zest", "vanilla"],
    source: "nutri-llm-library",
  },

  // ── UNITED KINGDOM ──────────────────────────────────────────────────────────
  {
    id: "uk-fish-chips",
    nameEn: "Fish and Chips",
    nameAr: "سمك مع البطاطس المقلية",
    cuisine: "British",
    region: "Western Europe",
    category: "main",
    nutrition: { calories: 680, protein: 32, carbs: 72, fat: 28, fiber: 4, sodium: 860 },
    tags: ["fried", "battered-fish", "pub-food", "classic"],
    allergens: ["fish", "wheat", "eggs"],
    cookTime: 40,
    difficulty: "medium",
    description: "Britain's national dish — golden beer-battered cod or haddock with chunky chips, mushy peas and malt vinegar.",
    ingredients: ["cod or haddock", "flour", "beer", "potatoes", "oil", "malt vinegar", "mushy peas", "salt", "tartar sauce"],
    source: "nutri-llm-library",
  },
  {
    id: "uk-full-english",
    nameEn: "Full English Breakfast",
    nameAr: "الفطور الإنجليزي الكامل",
    cuisine: "British",
    region: "Western Europe",
    category: "breakfast",
    nutrition: { calories: 820, protein: 42, carbs: 48, fat: 50, fiber: 5, sodium: 1400 },
    tags: ["eggs", "bacon", "sausage", "hearty"],
    allergens: ["wheat", "eggs", "dairy"],
    cookTime: 25,
    difficulty: "easy",
    description: "The great British fry-up — fried eggs, back bacon, sausages, baked beans, grilled tomatoes, black pudding and toast.",
    ingredients: ["eggs", "back bacon", "pork sausages", "baked beans", "tomatoes", "mushrooms", "black pudding", "toast", "butter"],
    source: "nutri-llm-library",
  },
  {
    id: "uk-shepherds-pie",
    nameEn: "Shepherd's Pie",
    nameAr: "فطيرة الراعي",
    cuisine: "British",
    region: "Western Europe",
    category: "main",
    nutrition: { calories: 450, protein: 26, carbs: 40, fat: 20, fiber: 5, sodium: 620 },
    tags: ["lamb", "mashed-potato", "baked", "comfort-food"],
    allergens: ["dairy"],
    cookTime: 60,
    difficulty: "medium",
    description: "A classic British bake of minced lamb and root vegetables in gravy, topped with a golden, buttery mashed potato crust.",
    ingredients: ["ground lamb", "carrots", "peas", "onion", "rosemary", "Worcestershire sauce", "potatoes", "butter", "cream", "cheese"],
    source: "nutri-llm-library",
  },
  {
    id: "uk-sticky-toffee",
    nameEn: "Sticky Toffee Pudding",
    nameAr: "بودينغ التوفي اللزج",
    cuisine: "British",
    region: "Western Europe",
    category: "dessert",
    nutrition: { calories: 480, protein: 6, carbs: 72, fat: 18, fiber: 2, sodium: 280 },
    tags: ["dates", "toffee-sauce", "baked", "indulgent"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 50,
    difficulty: "medium",
    description: "Moist date sponge cake drenched in a warm, buttery toffee sauce — the ultimate British dessert, often served with clotted cream.",
    ingredients: ["dates", "flour", "butter", "eggs", "brown sugar", "baking soda", "vanilla", "heavy cream", "golden syrup"],
    source: "nutri-llm-library",
  },

  // ── SPAIN (additional) ──────────────────────────────────────────────────────
  {
    id: "es-gazpacho",
    nameEn: "Gazpacho",
    nameAr: "غازباتشو",
    cuisine: "Spanish",
    region: "Mediterranean",
    category: "soup",
    nutrition: { calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 3, sodium: 420 },
    tags: ["cold-soup", "tomato", "vegan", "refreshing"],
    allergens: ["wheat"],
    cookTime: 15,
    difficulty: "easy",
    description: "Andalusia's chilled blended soup of ripe tomatoes, cucumber, pepper and garlic — a cooling summer staple drunk from a glass.",
    ingredients: ["ripe tomatoes", "cucumber", "red pepper", "garlic", "bread", "sherry vinegar", "olive oil", "salt"],
    source: "nutri-llm-library",
  },
  {
    id: "es-tortilla",
    nameEn: "Tortilla Española",
    nameAr: "أومليت إسبانية",
    cuisine: "Spanish",
    region: "Mediterranean",
    category: "main",
    nutrition: { calories: 350, protein: 16, carbs: 30, fat: 18, fiber: 2, sodium: 420 },
    tags: ["eggs", "potato", "onion", "tapas"],
    allergens: ["eggs"],
    cookTime: 45,
    difficulty: "medium",
    description: "Spain's beloved thick omelette of slowly caramelised potatoes and onion, cooked in olive oil and set to a custardy perfection.",
    ingredients: ["eggs", "potatoes", "onion", "olive oil", "salt"],
    source: "nutri-llm-library",
  },
  {
    id: "es-churros",
    nameEn: "Churros con Chocolate",
    nameAr: "تشوروس مع الشوكولاتة",
    cuisine: "Spanish",
    region: "Mediterranean",
    category: "dessert",
    nutrition: { calories: 380, protein: 6, carbs: 54, fat: 16, fiber: 2, sodium: 290 },
    tags: ["fried-dough", "chocolate", "breakfast", "street-food"],
    allergens: ["wheat", "eggs", "dairy"],
    cookTime: 30,
    difficulty: "easy",
    description: "Crispy ridged fried dough sticks dusted in cinnamon sugar, served with a cup of thick hot chocolate for dipping.",
    ingredients: ["flour", "water", "butter", "eggs", "oil", "sugar", "cinnamon", "dark chocolate", "milk", "cream"],
    source: "nutri-llm-library",
  },
  {
    id: "es-patatas-bravas",
    nameEn: "Patatas Bravas",
    nameAr: "بطاطس برافاس",
    cuisine: "Spanish",
    region: "Mediterranean",
    category: "appetizer",
    nutrition: { calories: 310, protein: 4, carbs: 42, fat: 14, fiber: 4, sodium: 490 },
    tags: ["tapas", "potato", "spicy-sauce", "fried"],
    allergens: ["eggs"],
    cookTime: 30,
    difficulty: "easy",
    description: "Crispy cubed fried potatoes slathered in a smoky paprika tomato sauce and creamy aioli — Spain's most addictive tapas.",
    ingredients: ["potatoes", "tomatoes", "paprika", "cayenne", "garlic", "olive oil", "aioli", "parsley"],
    source: "nutri-llm-library",
  },

  // ── FRANCE (additional) ─────────────────────────────────────────────────────
  {
    id: "fr-boeuf-bourguignon",
    nameEn: "Boeuf Bourguignon",
    nameAr: "لحم البقر البورغينيوني",
    cuisine: "French",
    region: "Western Europe",
    category: "main",
    nutrition: { calories: 520, protein: 38, carbs: 18, fat: 28, fiber: 3, sodium: 680 },
    tags: ["red-wine", "braised-beef", "slow-cooked", "classic"],
    allergens: ["dairy"],
    cookTime: 180,
    difficulty: "hard",
    description: "Burgundy's masterpiece — beef chuck braised in full-bodied red wine with pearl onions, lardons and mushrooms until meltingly tender.",
    ingredients: ["beef chuck", "Burgundy wine", "pearl onions", "bacon lardons", "mushrooms", "carrots", "garlic", "thyme", "bay leaves", "butter"],
    source: "nutri-llm-library",
  },
  {
    id: "fr-french-onion-soup",
    nameEn: "French Onion Soup",
    nameAr: "شوربة البصل الفرنسية",
    cuisine: "French",
    region: "Western Europe",
    category: "soup",
    nutrition: { calories: 380, protein: 16, carbs: 40, fat: 16, fiber: 3, sodium: 820 },
    tags: ["caramelised-onion", "gruyère", "bread", "bistro"],
    allergens: ["wheat", "dairy"],
    cookTime: 90,
    difficulty: "medium",
    description: "Deeply caramelised onions in a rich beef broth, crowned with toasted baguette and bubbling melted Gruyère cheese.",
    ingredients: ["onions", "beef broth", "baguette", "Gruyère", "butter", "thyme", "bay leaf", "white wine", "brandy"],
    source: "nutri-llm-library",
  },
  {
    id: "fr-crepes",
    nameEn: "Crêpes Suzette",
    nameAr: "كريب سوزيت",
    cuisine: "French",
    region: "Western Europe",
    category: "dessert",
    nutrition: { calories: 290, protein: 7, carbs: 42, fat: 10, fiber: 1, sodium: 180 },
    tags: ["flambé", "orange", "thin-pancake", "elegant"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 30,
    difficulty: "medium",
    description: "Delicate butter crêpes folded in a caramelised orange Grand Marnier sauce, theatrically flambéed at the table.",
    ingredients: ["flour", "eggs", "milk", "butter", "sugar", "orange zest", "Grand Marnier", "orange juice"],
    source: "nutri-llm-library",
  },
  {
    id: "fr-ratatouille",
    nameEn: "Ratatouille",
    nameAr: "راتاتوي",
    cuisine: "French",
    region: "Western Europe",
    category: "main",
    nutrition: { calories: 180, protein: 4, carbs: 22, fat: 8, fiber: 6, sodium: 360 },
    tags: ["vegetable-stew", "vegan", "provençal", "healthy"],
    allergens: [],
    cookTime: 60,
    difficulty: "easy",
    description: "Provence's colourful vegetable stew of tomatoes, eggplant, zucchini and peppers in herb-scented olive oil — vegan comfort food.",
    ingredients: ["eggplant", "zucchini", "tomatoes", "red pepper", "yellow pepper", "onion", "garlic", "thyme", "basil", "olive oil"],
    source: "nutri-llm-library",
  },

  // ── PORTUGAL ─────────────────────────────────────────────────────────────────
  {
    id: "pt-pastel-de-nata",
    nameEn: "Pastel de Nata",
    nameAr: "تارت الكاسترد البرتغالي",
    cuisine: "Portuguese",
    region: "Western Europe",
    category: "dessert",
    nutrition: { calories: 300, protein: 6, carbs: 38, fat: 14, fiber: 0, sodium: 120 },
    tags: ["custard-tart", "flaky-pastry", "cinnamon", "café"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 45,
    difficulty: "medium",
    description: "Lisbon's iconic caramelised custard tart in a flaky, crisp pastry shell — dusted with cinnamon and powdered sugar. Irresistible.",
    ingredients: ["puff pastry", "egg yolks", "cream", "sugar", "flour", "lemon zest", "cinnamon", "vanilla"],
    source: "nutri-llm-library",
  },
  {
    id: "pt-bacalhau",
    nameEn: "Bacalhau à Brás",
    nameAr: "سمك القد البرتغالي",
    cuisine: "Portuguese",
    region: "Western Europe",
    category: "main",
    nutrition: { calories: 450, protein: 34, carbs: 30, fat: 22, fiber: 3, sodium: 760 },
    tags: ["salt-cod", "eggs", "shoestring-fries", "traditional"],
    allergens: ["fish", "eggs"],
    cookTime: 40,
    difficulty: "medium",
    description: "Portugal's most beloved salt cod dish — shredded bacalhau with crispy shoestring potatoes, eggs and olives, all gently scrambled.",
    ingredients: ["salt cod", "potatoes", "eggs", "onion", "garlic", "olive oil", "black olives", "parsley"],
    source: "nutri-llm-library",
  },

  // ── SCANDINAVIA ──────────────────────────────────────────────────────────────
  {
    id: "se-kottbullar",
    nameEn: "Swedish Meatballs",
    nameAr: "كرات اللحم السويدية",
    cuisine: "Swedish",
    region: "Northern Europe",
    category: "main",
    nutrition: { calories: 480, protein: 28, carbs: 24, fat: 30, fiber: 2, sodium: 680 },
    tags: ["meatballs", "cream-sauce", "lingonberry", "classic"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 40,
    difficulty: "medium",
    description: "Tender spiced pork and beef meatballs in a silky cream gravy, served with lingonberry jam and fluffy mashed potatoes.",
    ingredients: ["ground pork", "ground beef", "breadcrumbs", "egg", "onion", "allspice", "nutmeg", "cream", "beef broth", "lingonberry jam"],
    source: "nutri-llm-library",
  },
  {
    id: "se-gravlax",
    nameEn: "Gravlax",
    nameAr: "جرافلاكس",
    cuisine: "Scandinavian",
    region: "Northern Europe",
    category: "appetizer",
    nutrition: { calories: 180, protein: 22, carbs: 2, fat: 9, fiber: 0, sodium: 1100 },
    tags: ["cured-salmon", "dill", "mustard-sauce", "elegant"],
    allergens: ["fish"],
    cookTime: 2880,
    difficulty: "easy",
    description: "Scandinavian dry-cured salmon with dill, salt, sugar and lemon — sliced paper-thin and served with sweet mustard dill sauce.",
    ingredients: ["salmon fillet", "salt", "sugar", "dill", "lemon zest", "white pepper", "mustard", "honey", "vinegar"],
    source: "nutri-llm-library",
  },

  // ── POLAND / EASTERN EUROPE ──────────────────────────────────────────────────
  {
    id: "pl-pierogi",
    nameEn: "Pierogi",
    nameAr: "بيروغي",
    cuisine: "Polish",
    region: "Eastern Europe",
    category: "main",
    nutrition: { calories: 420, protein: 14, carbs: 60, fat: 14, fiber: 3, sodium: 580 },
    tags: ["dumplings", "potato", "cheese", "pan-fried"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 60,
    difficulty: "medium",
    description: "Poland's beloved stuffed dumplings filled with potato and farmer's cheese, boiled then pan-fried in butter with caramelised onions.",
    ingredients: ["flour", "eggs", "water", "potatoes", "farmer's cheese", "onion", "butter", "sour cream"],
    source: "nutri-llm-library",
  },

  // ── RUSSIA ───────────────────────────────────────────────────────────────────
  {
    id: "ru-borscht",
    nameEn: "Borscht",
    nameAr: "بورشت",
    cuisine: "Russian",
    region: "Eastern Europe",
    category: "soup",
    nutrition: { calories: 220, protein: 10, carbs: 28, fat: 8, fiber: 5, sodium: 680 },
    tags: ["beet", "sour-cream", "hearty", "vegetable"],
    allergens: ["dairy"],
    cookTime: 90,
    difficulty: "medium",
    description: "Eastern Europe's iconic crimson beetroot soup with cabbage, potato, beef and a swirl of sour cream — warming and deeply nourishing.",
    ingredients: ["beets", "cabbage", "potatoes", "carrots", "onion", "beef", "tomato paste", "dill", "sour cream", "vinegar"],
    source: "nutri-llm-library",
  },
  {
    id: "ru-beef-stroganoff",
    nameEn: "Beef Stroganoff",
    nameAr: "ستروغانوف لحم البقر",
    cuisine: "Russian",
    region: "Eastern Europe",
    category: "main",
    nutrition: { calories: 490, protein: 32, carbs: 22, fat: 28, fiber: 2, sodium: 720 },
    tags: ["sour-cream", "mushrooms", "beef", "classic"],
    allergens: ["dairy", "wheat"],
    cookTime: 40,
    difficulty: "medium",
    description: "Tender strips of beef and mushrooms in a tangy sour cream sauce — a 19th-century Russian classic served over egg noodles.",
    ingredients: ["beef sirloin", "mushrooms", "onion", "sour cream", "beef broth", "Dijon mustard", "butter", "egg noodles", "dill"],
    source: "nutri-llm-library",
  },
  {
    id: "ru-pelmeni",
    nameEn: "Pelmeni",
    nameAr: "بيلميني",
    cuisine: "Russian",
    region: "Eastern Europe",
    category: "main",
    nutrition: { calories: 380, protein: 22, carbs: 42, fat: 12, fiber: 2, sodium: 540 },
    tags: ["dumplings", "pork-beef", "siberian", "comfort-food"],
    allergens: ["wheat", "eggs"],
    cookTime: 60,
    difficulty: "medium",
    description: "Siberian boiled meat dumplings — thin dough packed with a spiced pork and beef mix, served with sour cream and butter.",
    ingredients: ["flour", "eggs", "water", "ground pork", "ground beef", "onion", "garlic", "black pepper", "sour cream", "butter"],
    source: "nutri-llm-library",
  },

  // ── ARGENTINA ────────────────────────────────────────────────────────────────
  {
    id: "ar-empanadas",
    nameEn: "Empanadas",
    nameAr: "إمباناداس",
    cuisine: "Argentine",
    region: "Latin America",
    category: "appetizer",
    nutrition: { calories: 340, protein: 16, carbs: 36, fat: 14, fiber: 2, sodium: 520 },
    tags: ["stuffed-pastry", "baked-or-fried", "beef", "street-food"],
    allergens: ["wheat", "eggs"],
    cookTime: 60,
    difficulty: "medium",
    description: "Golden pastry pockets filled with spiced ground beef, hard-boiled egg and olives — a beloved Argentine street food and party staple.",
    ingredients: ["flour", "butter", "eggs", "ground beef", "onion", "cumin", "paprika", "hard-boiled eggs", "green olives", "raisins"],
    source: "nutri-llm-library",
  },
  {
    id: "ar-asado",
    nameEn: "Argentine Asado",
    nameAr: "أسادو أرجنتيني",
    cuisine: "Argentine",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 650, protein: 52, carbs: 0, fat: 46, fiber: 0, sodium: 420 },
    tags: ["bbq", "beef", "wood-fire", "national-dish"],
    allergens: [],
    cookTime: 180,
    difficulty: "medium",
    description: "Argentina's sacred barbecue tradition — beef ribs, chorizo and offal slow-grilled over wood embers, served with chimichurri.",
    ingredients: ["beef ribs", "short ribs", "chorizo", "morcilla", "chimichurri", "salt", "wood or charcoal"],
    source: "nutri-llm-library",
  },

  // ── CARIBBEAN ────────────────────────────────────────────────────────────────
  {
    id: "jm-jerk-chicken",
    nameEn: "Jerk Chicken",
    nameAr: "دجاج جيرك",
    cuisine: "Jamaican",
    region: "Caribbean",
    category: "main",
    nutrition: { calories: 420, protein: 38, carbs: 8, fat: 24, fiber: 2, sodium: 820 },
    tags: ["scotch-bonnet", "allspice", "grilled", "smoky"],
    allergens: [],
    cookTime: 120,
    difficulty: "medium",
    description: "Jamaican jerk chicken marinated overnight in scotch bonnet, allspice and thyme, then slow-grilled over pimento wood for a smoky, fiery result.",
    ingredients: ["chicken", "scotch bonnet", "allspice", "thyme", "garlic", "ginger", "soy sauce", "lime", "brown sugar", "cinnamon"],
    source: "nutri-llm-library",
  },
  {
    id: "tt-doubles",
    nameEn: "Doubles",
    nameAr: "دابلز",
    cuisine: "Trinidadian",
    region: "Caribbean",
    category: "breakfast",
    nutrition: { calories: 320, protein: 10, carbs: 52, fat: 8, fiber: 6, sodium: 580 },
    tags: ["street-food", "chickpea-curry", "bara", "vegan"],
    allergens: ["wheat"],
    cookTime: 45,
    difficulty: "medium",
    description: "Trinidad's iconic breakfast street food — two soft fried bara flatbreads stacked with curried chickpeas, tamarind and pepper sauce.",
    ingredients: ["flour", "yeast", "turmeric", "chickpeas", "curry powder", "cumin", "garlic", "tamarind sauce", "pepper sauce", "cilantro"],
    source: "nutri-llm-library",
  },

  // ── PHILIPPINES ──────────────────────────────────────────────────────────────
  {
    id: "ph-adobo",
    nameEn: "Chicken Adobo",
    nameAr: "دجاج أدوبو",
    cuisine: "Filipino",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 410, protein: 34, carbs: 8, fat: 24, fiber: 1, sodium: 960 },
    tags: ["vinegar", "soy-sauce", "braised", "garlic"],
    allergens: ["soy"],
    cookTime: 60,
    difficulty: "easy",
    description: "The Philippines' national dish — chicken braised in vinegar, soy sauce, garlic and bay leaves until deeply savoury and fork-tender.",
    ingredients: ["chicken thighs", "soy sauce", "white vinegar", "garlic", "bay leaves", "black peppercorns", "coconut milk"],
    source: "nutri-llm-library",
  },
  {
    id: "ph-sinigang",
    nameEn: "Sinigang",
    nameAr: "سينيغانغ",
    cuisine: "Filipino",
    region: "Southeast Asia",
    category: "soup",
    nutrition: { calories: 290, protein: 24, carbs: 18, fat: 10, fiber: 5, sodium: 820 },
    tags: ["tamarind", "sour-soup", "pork", "vegetables"],
    allergens: ["fish"],
    cookTime: 60,
    difficulty: "medium",
    description: "A deeply sour and savoury Filipino tamarind broth with pork ribs, eggplant, water spinach and tomatoes — the ultimate comfort soup.",
    ingredients: ["pork ribs", "tamarind", "tomatoes", "eggplant", "kangkong", "radish", "green beans", "fish sauce", "onion"],
    source: "nutri-llm-library",
  },
  {
    id: "ph-lechon",
    nameEn: "Lechon",
    nameAr: "ليتشون",
    cuisine: "Filipino",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 580, protein: 42, carbs: 4, fat: 42, fiber: 0, sodium: 720 },
    tags: ["roast-pig", "crispy-skin", "festive", "celebratory"],
    allergens: [],
    cookTime: 480,
    difficulty: "hard",
    description: "Philippines' crown jewel of celebration feasts — whole pig slow-roasted over charcoal for hours until the skin is shatteringly crisp.",
    ingredients: ["whole pig", "lemongrass", "garlic", "onion", "bay leaves", "salt", "pepper", "liver sauce"],
    source: "nutri-llm-library",
  },

  // ── MALAYSIA ─────────────────────────────────────────────────────────────────
  {
    id: "my-laksa",
    nameEn: "Laksa",
    nameAr: "لاكسا",
    cuisine: "Malaysian",
    region: "Southeast Asia",
    category: "soup",
    nutrition: { calories: 520, protein: 22, carbs: 58, fat: 22, fiber: 3, sodium: 1080 },
    tags: ["coconut-milk", "noodles", "spicy", "shrimp-paste"],
    allergens: ["shellfish", "fish", "wheat"],
    cookTime: 60,
    difficulty: "medium",
    description: "A fiery Peranakan noodle soup in a rich coconut curry broth with shrimp, tofu puffs, bean sprouts and sambal.",
    ingredients: ["rice noodles", "coconut milk", "shrimp", "tofu puffs", "laksa paste", "galangal", "lemongrass", "bean sprouts", "shrimp paste", "lime"],
    source: "nutri-llm-library",
  },
  {
    id: "my-nasi-lemak",
    nameEn: "Nasi Lemak",
    nameAr: "ناسي ليماك",
    cuisine: "Malaysian",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 550, protein: 22, carbs: 64, fat: 22, fiber: 4, sodium: 760 },
    tags: ["coconut-rice", "sambal", "anchovies", "national-dish"],
    allergens: ["fish", "eggs"],
    cookTime: 60,
    difficulty: "medium",
    description: "Malaysia's national dish — fragrant coconut rice served with crispy anchovies, peanuts, cucumber, hard-boiled egg and fiery sambal.",
    ingredients: ["rice", "coconut milk", "pandan leaves", "anchovies", "peanuts", "cucumber", "egg", "sambal chili paste"],
    source: "nutri-llm-library",
  },
  {
    id: "sg-char-kway-teow",
    nameEn: "Char Kway Teow",
    nameAr: "تشار كواي تيو",
    cuisine: "Singaporean",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 530, protein: 20, carbs: 66, fat: 20, fiber: 3, sodium: 1100 },
    tags: ["wok-fried-noodles", "smoky", "shrimp", "hawker"],
    allergens: ["wheat", "soy", "shellfish", "eggs"],
    cookTime: 15,
    difficulty: "medium",
    description: "Singapore's wok-charred flat rice noodles with prawns, Chinese sausage, egg, bean sprouts and dark soy sauce — wok hei essential.",
    ingredients: ["flat rice noodles", "shrimp", "Chinese sausage", "egg", "bean sprouts", "dark soy sauce", "fish sauce", "chili", "lard"],
    source: "nutri-llm-library",
  },

  // ── JAPAN (additional) ──────────────────────────────────────────────────────
  {
    id: "jp-yakitori",
    nameEn: "Yakitori",
    nameAr: "ياكيتوري",
    cuisine: "Japanese",
    region: "East Asia",
    category: "appetizer",
    nutrition: { calories: 260, protein: 28, carbs: 10, fat: 10, fiber: 0, sodium: 680 },
    tags: ["grilled-skewers", "chicken", "tare-sauce", "izakaya"],
    allergens: ["soy", "wheat"],
    cookTime: 30,
    difficulty: "easy",
    description: "Bite-sized chicken pieces grilled over binchotan charcoal on bamboo skewers, glazed with sweet tare sauce — the soul of Japanese izakaya.",
    ingredients: ["chicken thigh", "chicken skin", "green onion", "soy sauce", "mirin", "sake", "sugar", "bamboo skewers"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-okonomiyaki",
    nameEn: "Okonomiyaki",
    nameAr: "أوكونوميياكي",
    cuisine: "Japanese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 400, protein: 18, carbs: 44, fat: 16, fiber: 3, sodium: 780 },
    tags: ["savory-pancake", "cabbage", "osaka", "street-food"],
    allergens: ["wheat", "eggs", "fish"],
    cookTime: 25,
    difficulty: "medium",
    description: "Osaka's thick savory cabbage pancake loaded with pork belly, shrimp and pickled ginger, topped with mayo and bonito flakes.",
    ingredients: ["flour", "eggs", "dashi", "cabbage", "pork belly", "shrimp", "pickled ginger", "okonomiyaki sauce", "mayo", "bonito flakes"],
    source: "nutri-llm-library",
  },
  {
    id: "jp-onigiri",
    nameEn: "Onigiri",
    nameAr: "أونيغيري",
    cuisine: "Japanese",
    region: "East Asia",
    category: "snack",
    nutrition: { calories: 190, protein: 5, carbs: 38, fat: 2, fiber: 1, sodium: 380 },
    tags: ["rice-ball", "nori", "portable", "convenience"],
    allergens: ["fish"],
    cookTime: 20,
    difficulty: "easy",
    description: "Hand-pressed rice triangles filled with salmon, tuna mayo or pickled plum, wrapped in crisp nori — Japan's ultimate portable snack.",
    ingredients: ["sushi rice", "nori", "salt", "salmon flakes or tuna or umeboshi"],
    source: "nutri-llm-library",
  },

  // ── CHINA (additional) ──────────────────────────────────────────────────────
  {
    id: "cn-xiao-long-bao",
    nameEn: "Xiao Long Bao",
    nameAr: "شياو لونج باو",
    cuisine: "Shanghainese",
    region: "East Asia",
    category: "appetizer",
    nutrition: { calories: 280, protein: 14, carbs: 30, fat: 10, fiber: 1, sodium: 560 },
    tags: ["soup-dumplings", "pork", "steamed", "delicate"],
    allergens: ["wheat", "soy"],
    cookTime: 90,
    difficulty: "hard",
    description: "Shanghai's legendary soup dumplings — pleated thin dough parcels each hiding a rich pork-and-ginger filling plus a whole spoonful of hot broth.",
    ingredients: ["flour", "water", "pork", "ginger", "soy sauce", "Shaoxing wine", "pork gelatin", "sesame oil", "green onion"],
    source: "nutri-llm-library",
  },
  {
    id: "cn-fried-rice",
    nameEn: "Yangzhou Fried Rice",
    nameAr: "أرز مقلي يانغتشو",
    cuisine: "Chinese",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 420, protein: 18, carbs: 58, fat: 14, fiber: 2, sodium: 820 },
    tags: ["fried-rice", "wok-hei", "egg", "shrimp"],
    allergens: ["eggs", "soy", "shellfish"],
    cookTime: 20,
    difficulty: "medium",
    description: "Wok-tossed day-old rice with shrimp, char siu pork, egg, peas and carrots — the gold standard of Chinese fried rice with perfect wok hei.",
    ingredients: ["day-old rice", "shrimp", "char siu pork", "eggs", "peas", "carrots", "green onion", "soy sauce", "sesame oil"],
    source: "nutri-llm-library",
  },

  // ── KOREA (additional) ──────────────────────────────────────────────────────
  {
    id: "kr-korean-fried-chicken",
    nameEn: "Korean Fried Chicken",
    nameAr: "دجاج مقلي كوري",
    cuisine: "Korean",
    region: "East Asia",
    category: "main",
    nutrition: { calories: 540, protein: 36, carbs: 38, fat: 26, fiber: 2, sodium: 980 },
    tags: ["double-fried", "crispy", "sweet-spicy-glaze", "chimaek"],
    allergens: ["wheat", "soy", "sesame"],
    cookTime: 45,
    difficulty: "medium",
    description: "Twice-fried Korean chicken with an impossibly thin, crunchy crust glazed in yangnyeom sweet-spicy sauce or soy-garlic — served with beer.",
    ingredients: ["chicken wings", "potato starch", "gochujang", "soy sauce", "garlic", "ginger", "honey", "rice wine", "sesame seeds"],
    source: "nutri-llm-library",
  },

  // ── THAILAND (additional) ────────────────────────────────────────────────────
  {
    id: "th-mango-sticky-rice",
    nameEn: "Mango Sticky Rice",
    nameAr: "الأرز اللزج بالمانجو",
    cuisine: "Thai",
    region: "Southeast Asia",
    category: "dessert",
    nutrition: { calories: 380, protein: 5, carbs: 72, fat: 8, fiber: 3, sodium: 180 },
    tags: ["glutinous-rice", "coconut-cream", "mango", "sweet"],
    allergens: [],
    cookTime: 45,
    difficulty: "easy",
    description: "Thailand's most beloved dessert — warm coconut-soaked glutinous rice paired with ripe golden mango slices and a salted coconut cream drizzle.",
    ingredients: ["glutinous rice", "coconut milk", "sugar", "salt", "ripe mango", "pandan leaves", "sesame seeds"],
    source: "nutri-llm-library",
  },
  {
    id: "th-pad-see-ew",
    nameEn: "Pad See Ew",
    nameAr: "باد سي إيو",
    cuisine: "Thai",
    region: "Southeast Asia",
    category: "main",
    nutrition: { calories: 480, protein: 22, carbs: 60, fat: 16, fiber: 2, sodium: 1050 },
    tags: ["flat-noodles", "dark-soy", "egg", "wok-fried"],
    allergens: ["wheat", "soy", "eggs", "fish"],
    cookTime: 15,
    difficulty: "easy",
    description: "Wide flat rice noodles stir-fried in dark sweet soy sauce with egg, Chinese broccoli and chicken — Thai comfort food done fast.",
    ingredients: ["flat rice noodles", "chicken", "egg", "Chinese broccoli", "dark soy sauce", "oyster sauce", "fish sauce", "garlic", "oil"],
    source: "nutri-llm-library",
  },

  // ── VIETNAM (additional) ─────────────────────────────────────────────────────
  {
    id: "vn-goi-cuon",
    nameEn: "Vietnamese Spring Rolls",
    nameAr: "لفائف الربيع الفيتنامية",
    cuisine: "Vietnamese",
    region: "Southeast Asia",
    category: "appetizer",
    nutrition: { calories: 180, protein: 12, carbs: 24, fat: 3, fiber: 2, sodium: 420 },
    tags: ["fresh-rolls", "shrimp", "rice-paper", "healthy"],
    allergens: ["shellfish", "fish", "peanuts"],
    cookTime: 20,
    difficulty: "easy",
    description: "Translucent rice paper rolls packed with poached shrimp, pork, rice noodles, mint and lettuce — served with hoisin peanut sauce.",
    ingredients: ["rice paper", "shrimp", "pork belly", "rice vermicelli", "lettuce", "mint", "basil", "hoisin sauce", "peanuts", "lime"],
    source: "nutri-llm-library",
  },

  // ── INDIA (additional) ───────────────────────────────────────────────────────
  {
    id: "in-tandoori-chicken",
    nameEn: "Tandoori Chicken",
    nameAr: "دجاج تندوري",
    cuisine: "Indian",
    region: "South Asia",
    category: "main",
    nutrition: { calories: 340, protein: 38, carbs: 8, fat: 16, fiber: 1, sodium: 680 },
    tags: ["yogurt-marinated", "charred", "smoky", "high-protein"],
    allergens: ["dairy"],
    cookTime: 60,
    difficulty: "medium",
    description: "Chicken marinated in spiced yogurt with ginger, garlic and Kashmiri chili, cooked at extreme heat in a tandoor clay oven for a beautiful char.",
    ingredients: ["chicken", "yogurt", "Kashmiri chili", "cumin", "coriander", "garlic", "ginger", "garam masala", "lemon juice", "turmeric"],
    source: "nutri-llm-library",
  },
  {
    id: "in-naan",
    nameEn: "Naan",
    nameAr: "نان",
    cuisine: "Indian",
    region: "South Asia",
    category: "side",
    nutrition: { calories: 280, protein: 9, carbs: 48, fat: 6, fiber: 2, sodium: 480 },
    tags: ["flatbread", "leavened", "tandoor", "butter"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 30,
    difficulty: "medium",
    description: "Pillowy leavened flatbread cooked at blistering heat in a tandoor clay oven, brushed with butter and scattered with garlic and cilantro.",
    ingredients: ["flour", "yogurt", "yeast", "milk", "egg", "butter", "garlic", "cilantro", "salt"],
    source: "nutri-llm-library",
  },

  // ── USA (additional) ─────────────────────────────────────────────────────────
  {
    id: "us-cheeseburger",
    nameEn: "Classic Cheeseburger",
    nameAr: "برغر بالجبن",
    cuisine: "American",
    region: "North America",
    category: "main",
    nutrition: { calories: 640, protein: 36, carbs: 42, fat: 36, fiber: 2, sodium: 960 },
    tags: ["beef-patty", "cheddar", "brioche", "classic"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 20,
    difficulty: "easy",
    description: "A griddled ground beef patty with melted American cheddar, lettuce, tomato, onion and pickles on a toasted brioche bun.",
    ingredients: ["ground beef", "American cheese", "brioche bun", "lettuce", "tomato", "onion", "pickles", "ketchup", "mustard", "mayo"],
    source: "nutri-llm-library",
  },
  {
    id: "us-mac-cheese",
    nameEn: "Mac and Cheese",
    nameAr: "مكرونة بالجبن",
    cuisine: "American",
    region: "North America",
    category: "main",
    nutrition: { calories: 520, protein: 20, carbs: 58, fat: 22, fiber: 2, sodium: 680 },
    tags: ["pasta", "cheese-sauce", "comfort-food", "baked"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 40,
    difficulty: "easy",
    description: "Elbow macaroni bathed in a rich béchamel with sharp cheddar and Gruyère, baked until golden and bubbly with a breadcrumb crust.",
    ingredients: ["macaroni", "sharp cheddar", "Gruyère", "butter", "flour", "milk", "Dijon mustard", "breadcrumbs", "paprika"],
    source: "nutri-llm-library",
  },

  // ── BRAZIL (additional) ──────────────────────────────────────────────────────
  {
    id: "br-churrasco",
    nameEn: "Churrasco",
    nameAr: "تشوراسكو",
    cuisine: "Brazilian",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 600, protein: 48, carbs: 0, fat: 44, fiber: 0, sodium: 480 },
    tags: ["bbq", "beef", "skewered", "gaucho"],
    allergens: [],
    cookTime: 60,
    difficulty: "medium",
    description: "Brazilian gaucho-style barbecue — thick picanha beef rump cap skewered and slow-grilled over glowing embers, served tableside rodízio style.",
    ingredients: ["picanha (rump cap)", "coarse salt", "garlic", "chimichurri", "pão de queijo", "farofa"],
    source: "nutri-llm-library",
  },
  {
    id: "br-brigadeiro",
    nameEn: "Brigadeiro",
    nameAr: "بريغاديرو",
    cuisine: "Brazilian",
    region: "Latin America",
    category: "dessert",
    nutrition: { calories: 140, protein: 2, carbs: 22, fat: 5, fiber: 0, sodium: 60 },
    tags: ["chocolate-truffle", "birthday", "condensed-milk", "no-bake"],
    allergens: ["dairy"],
    cookTime: 20,
    difficulty: "easy",
    description: "Brazil's iconic chocolate truffle — sweetened condensed milk cooked with cocoa and butter, rolled into balls and coated in chocolate sprinkles.",
    ingredients: ["sweetened condensed milk", "cocoa powder", "butter", "chocolate sprinkles"],
    source: "nutri-llm-library",
  },

  // ── MEXICO (additional) ──────────────────────────────────────────────────────
  {
    id: "mx-pozole",
    nameEn: "Pozole Rojo",
    nameAr: "بوزولي أحمر",
    cuisine: "Mexican",
    region: "Latin America",
    category: "soup",
    nutrition: { calories: 390, protein: 26, carbs: 44, fat: 12, fiber: 6, sodium: 820 },
    tags: ["hominy", "pork", "red-chili", "festive"],
    allergens: [],
    cookTime: 180,
    difficulty: "medium",
    description: "Mexico's ancient ceremonial soup — slow-simmered pork with bloomed hominy corn in a smoky ancho and guajillo chili broth, served with crunchy toppings.",
    ingredients: ["pork shoulder", "hominy corn", "ancho chili", "guajillo chili", "garlic", "onion", "oregano", "radishes", "shredded cabbage", "lime"],
    source: "nutri-llm-library",
  },
  {
    id: "mx-enchiladas",
    nameEn: "Enchiladas Verdes",
    nameAr: "إنشيلاداس خضراء",
    cuisine: "Mexican",
    region: "Latin America",
    category: "main",
    nutrition: { calories: 430, protein: 26, carbs: 42, fat: 18, fiber: 4, sodium: 740 },
    tags: ["tomatillo-sauce", "chicken", "corn-tortilla", "cheese"],
    allergens: ["wheat", "dairy", "eggs"],
    cookTime: 50,
    difficulty: "medium",
    description: "Corn tortillas stuffed with shredded chicken, rolled and smothered in a bright tomatillo salsa verde, then baked with cheese and crema.",
    ingredients: ["corn tortillas", "chicken", "tomatillos", "jalapeños", "garlic", "cilantro", "crema", "Oaxacan cheese", "onion"],
    source: "nutri-llm-library",
  },
];
